### ISSUE TITLE
Something about grain128

### ISSUE THREAD

**Issue by xianmd** [Noxet/Grain-128AEAD#1]
Before beginning ,i have to admit that i'm a Chinese student .So there might be some mistakes in my sentences ,and i even don't know if you can see this .Anyway i apologize first .
Here is the question : it's quiet difficult to find an standard file to prove accuracy .As a result ,i don't know if this code is correct or not.Besides there some difference between the code and my homework instruction ,for example ,when we first initialize the register LFSR ,mine shows that we should set the 96-128 all 1，but yours apparently set 96-127 as 1  and  128 as 0.I couldn't understand it because i don't have a standard .Could you please tell me if you can prove this code is correct or give me a standard about the registers during the initialization ?Sorry again about these questions .Thank you !

**Comment by Noxet** [comment]
Hi, I think you have looked at the old version, Grain-128: https://www.ecrypt.eu.org/stream/p3ciphers/grain/Grain128_p3.pdf
This version should NOT be used.

The latest version of grain, Grain-128AEAD should be initialized as I did in the code, see the documentation here: https://lup.lub.lu.se/search/publication/0806c8ca-a778-4abc-bf0d-4d64953bcaf1

If you can not access the paper, the NIST version is found here: https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/round-2/spec-doc-rnd2/grain-128aead-spec-round2.pdf

p.s.
We do not load from 96-128 as this is 33 bits, the last register is denoted 127 :)

**Comment by xianmd** [comment]
Thank you very much !You can't imagine how excited i'm! Actually, I didn't even think that you might reply.Anyway,it helps me a lot,and it might take me some time to read this.My poor English,you know.At last, thank you again and wish you have a good day!

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jonathan Sönnerup"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 晚上6:49
收件人:&nbsp;"Noxet/Grain-128AEAD"<Grain-128AEAD@noreply.github.com&gt;;
抄送:&nbsp;"飞阳"<562788756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Noxet/Grain-128AEAD] Something about grain128 (#1)




Hi, I think you have looked at the old version, Grain-128: https://www.ecrypt.eu.org/stream/p3ciphers/grain/Grain128_p3.pdf
 This version should NOT be used.
 
The latest version of grain, Grain-128AEAD should initialize as I did in the code, see the documentation here: https://lup.lub.lu.se/search/publication/0806c8ca-a778-4abc-bf0d-4d64953bcaf1
 
If you can not access the paper, the NIST version is found here: https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/round-2/spec-doc-rnd2/grain-128aead-spec-round2.pdf
 
p.s.
 We do not load from 96-128 as this is 33 bits, the last register is denoted 127 :)

**Comment by Noxet** [comment]
No problem.
What is your homework about? It is nice if you use Grain in school.
Just email me if you need more help

**Comment by xianmd** [comment]
Hi it's me again.In recent days,I looked through the NIST standard and your code.I believe that I have a little understanding about Grain128.But there's still something about the NIST paper and your code that confuses me.And I will try my best to explain them clearly.I hope you can teach me if you are not busy .Still, I feel quiet sorry for bothing you .The questions are in the appendix .








&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; BEST WISHES TO YOU
------------------ 原始邮件 ------------------
发件人:&nbsp;"Jonathan Sönnerup"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 晚上7:09
收件人:&nbsp;"Noxet/Grain-128AEAD"<Grain-128AEAD@noreply.github.com&gt;;
抄送:&nbsp;"飞阳"<562788756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Noxet/Grain-128AEAD] Something about grain128 (#1)





 
No problem.
 What is your homework about? It is nice if you use Grain in school.
 Just email me if you need more help

**Comment by Noxet** [comment]
Hi. I did not get an appendix, maybe you forgot to attach it?
You can simply add your questions here as a list or something, then it is easier to answer them one by one.
